! DESCRIP.MMS - build GNU diffutils for OpenVMS (IA64, x86-64)
!
! Run from the top of the prepared source tree via [.VMS]BUILD.COM, which
! passes ARCH (IA64 or X86_64) and creates the output directories.  Source
! lists and per-object rules come from [.VMS]SOURCES.MMS, and each program's
! objects from [.VMS]PROGS.MMS, both generated by tools/prepare.sh.

.IFDEF ARCH
.ELSE
ARCH = IA64
.ENDIF

OBJ = [.OBJ_$(ARCH)]
LOBJ = [.OBJ_$(ARCH).LIB]
BIN = [.BIN_$(ARCH)]

.INCLUDE [.VMS]SOURCES.MMS
.INCLUDE [.VMS]PROGS.MMS

LIB = $(OBJ)LIBDIFFUTILS.OLB

CC = CC
CFLAGS = $(CC_QUAL)/NOLIST/INCLUDE_DIRECTORY=("./lib","./src","./vms")-
	/DEFINE=($(CC_DEFS),HAVE_CONFIG_H)

ALL : $(BIN)CMP.EXE, $(BIN)DIFF.EXE, $(BIN)DIFF3.EXE, $(BIN)SDIFF.EXE
	@ CONTINUE

! "-": LINK ends with a warning status (%ILINK-W-COMPWARN) when modules
! compiled with VSI C's benign warnings; tools/build.sh fails the build on
! real link errors and undefined symbols.
$(BIN)CMP.EXE : $(CMP_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)CMP.MAP/FULL $(CMP_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(BIN)DIFF.EXE : $(DIFF_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)DIFF.MAP/FULL $(DIFF_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(BIN)DIFF3.EXE : $(DIFF3_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)DIFF3.MAP/FULL $(DIFF3_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(BIN)SDIFF.EXE : $(SDIFF_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)SDIFF.MAP/FULL $(SDIFF_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(LIB) : $(LIB_OBJS)
	IF F$SEARCH("$(MMS$TARGET)") .EQS. "" THEN LIBRARY/CREATE/OBJECT $(MMS$TARGET)
	LIBRARY/REPLACE/OBJECT $(MMS$TARGET) $(LOBJ)*.OBJ

CLEAN :
	IF F$SEARCH("$(LOBJ)*.*") .NES. "" THEN DELETE/NOLOG $(LOBJ)*.*;*
	IF F$SEARCH("$(OBJ)*.OBJ") .NES. "" THEN DELETE/NOLOG $(OBJ)*.OBJ;*,*.OLB;*,*.MAP;*
	IF F$SEARCH("$(BIN)*.*") .NES. "" THEN DELETE/NOLOG $(BIN)*.*;*
